format_version: 2

pipelines:
  demopipe:
    group: simple
    parameters:
      seconds_num: 3
    materials:
      mygit:
        git: https://github.com/Ghotrix/getting-started-repo.git
    stages:
      - build:
          clean_workspace: true
          jobs:
            main:
              tasks:
                - exec:
                    command: ./build
              artifacts:
                - build:
                    source: my-artifact.html
                    destination: build
